apiVersion: v1
kind: Namespace
metadata:
  name: test

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
  namespace: test
  labels:
    app: pyapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
      - name: pyapp
        image: test_app:1
        ports:
        - containerPort: 8000
        env:
        - name: UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /docs
              port: 8000
        livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /id
              port: 8000

---

apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: test-service
spec:
  type: ClusterIP
  selector:
    app: pyapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000